# Generated by Django 3.2.20 on 2023-08-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('number_of_students', models.IntegerField(default=' ')),
                ('number_of_teachers', models.IntegerField(default=' ')),
            ],
        ),
    ]
