# Generated by Django 3.2.20 on 2023-08-30 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schoolmodels',
            table='app1_school',
        ),
    ]
