# Generated by Django 3.2.20 on 2023-08-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_schoolmodels_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('number_of_students', models.IntegerField(default=50)),
                ('number_of_teachers', models.IntegerField(default=5)),
            ],
            options={
                'db_table': 'app1_university',
            },
        ),
    ]
