# Generated by Django 3.2.20 on 2023-09-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_university'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='university',
            table=None,
        ),
    ]
